export default {
  CHOOSE_GAME: 'CHOOSE_GAME',
  CHOOSE_TOURNAMENT: 'CHOOSE_TOURNAMENT',
  START_READY_TIME: 'START_READY_TIME',
  START_ROUND: 'START_ROUND',
  SET_RESULT: 'SET_RESULT',
  JOIN_TOURNAMENT: 'JOIN_TOURNAMENT',
};
